### ISSUE TITLE
No route or template set for noAuth hook, using "/"

### ISSUE THREAD

**Issue by meteorjs3000** [zimme/meteor-iron-router-auth#17]
When starting my app, I encounter the error

    WARN: No route or template set for noAuth hook, using "/"

I did not set anything for `noAuth`, this is necessary to do so? What does `noAuth` do, I cant quite figure out from the examples...

Here's my plugin settings

	Router.plugin('auth', {
		authenticate: {
			route: 'login'
		},
		except: ['login']
	})

**Comment by zimme** [comment]
It's only a warning saying that the `noAuth` hook will use the path "/" as neither `dashboard` or `home` were set.

It's not necessary to set the `dashboard` or `home` option on `noAuth` but if you wan't to control the redirect you'll have to.

**Comment by zimme** [comment]
Just reopen the issue if the answer isn't enough.

**Comment by guilhermedecampo** [comment]
Hey @zimme thanks for the awesome work!

I'm receiving this error, but when I really add the `noAuth`

```
Router.route('/', {
  name: 'home',
  controller: 'HomeController',
  action: 'action',
  where: 'client',
  // when access
  noAuth: {
    template: 'signin'
  },
  onBeforeAction: ['noAuth']
});
```
You can see in the screenshot
![screen shot 2015-04-07 at 4 54 51 pm](https://cloud.githubusercontent.com/assets/4806269/7032121/d4e0b166-dd46-11e4-9b5a-48ee37daf2e0.png)

I also add the `authenticate` filter

```
// With options on use
Router.onBeforeAction('authenticate', {
  authenticate: {
    route: 'signChoose',
  },
  except: ['home', 'signChoose', 'signUp', 'signIn', 'createProfile']
});
```

**Comment by zimme** [comment]
Ok, I see one thing that's wrong...

The `noAuth` hook don't have the `route` or `template` options but have `home` and/or `dashboard` options, which should be route names.
```
noAuth: {
  dashboard: 'landingPageAfterLogin',
  home: 'landingPageBeforeLogin'
}
```
It tries to use `dashboard` first then `home` and if none is set, it falls back to the route with path `/`. That's what the warning is telling you. It's only a warning just to remind you you didn't set `dashboard` or `home` for the `noAuth` hook options and that it will use the path `/` instead.

Also the core of the problem is that you're using the `noAuth` hook on the home route which tries to redirect you back to either `dashboard`, `home` or `/` if you're logged in.

I've come to realize `noAuth` wasn't a good name for the hook as people might thing it's what they should use on route's where they don't want authentication. When in fact it's the hook you should use on routes where you wan't logged in users not to have access to.

i.e. When an already authenticated user (logged in) goes to the `signIn` route you wan't him to be redirected to the `dashboard` instead.

In your case it's enough to just exclude `home` from the `authenticate` hook and there's no requirement for authentication on the `home` route.

**Comment by zimme** [comment]
So what the current setup for you is doing is pushing you into an endless loop because `home` is redirecting you to `/` which is `home`
