### ISSUE TITLE
Can't get 'except' to work with route parameters

### ISSUE THREAD

**Issue by mordra** [zimme/meteor-iron-router-auth#25]
I'm using the auth plugin:
```
Router.plugin('auth', {
    except: ['index', 'about', 'login', 'guest']
});
```

And if my guest route looks like this, it's fine:
```
Router.route('/guest', 'newMessage');
```

However, the moment I change it to this, it starts to send me to my auth page:
```
Router.route('/guest/:option', 'newMessage');
// or
Router.route('/guest/:option?', 'newMessage');
```

Do I need to specify all sub routes? Or am I doing something wrong re except?

**Comment by zimme** [comment]
So the strings in `except` isn't route paths but they are route names so your routes would need to look like this.
```js
Router.route('/guest', 'newMessage, { name: 'guest' });
```
or as I would do it
```js
Router.route('/guest', {
  name: 'guest',
  template: 'newMessage'
});
```

**Comment by zimme** [comment]
I think the reason it might work with this `Router.route('/guest', 'newMessage');` is because `iron:router` might be using `/guest` without the slash as the route's name. Once you add dynamic parts to the route's path the "generated" name is different and that's why it's not matching anymore.

So when using this package it's best to manually give your routes a name.

I'm closing, just @mention me if this isn't resolved by my answer.
